kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # For Ingress (HTTP and HTTPS)
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

      # For frontend NodePort service
      - containerPort: 30435
        hostPort: 30435
        protocol: TCP

      # For backend NodePort service
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP

      # For Postgres access (only if you need it from host)
      - containerPort: 5432
        hostPort: 5432
        protocol: TCP
