apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: armoire-app
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: armoire-frontend
      context: frontEnd
      docker:
        dockerfile: Dockerfile
    - image: armoire-backend
      context: backEnd
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/frontend-deployment.yml
    - k8s/backend-deployment.yml
    - k8s/frontend-ingress.yml
    - k8s/backend-ingress.yml
    - k8s/postgres-deployment.yml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: frontend
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: backend
    port: 8000
    localPort: 8000
